first_odom_topic_name: /point_lio/odom
# second_odom_topic_name: /uav1/hw_api/odometry
second_odom_topic_name: /ov_msckf/odomimu
first_ekf_eig_topic_name: /point_lio/eig2
second_ekf_eig_topic_name: /ov_msckf/eig
cmd_acc_topic_name: /uav1/control_manager/estimator_input
ground_truth_topic_name: /mavros/global_position/local
node_name: /point_lio

num_states: 21
num_inputs: 6
tau: 0.1
Delta_t: 0.01

# lambda_xyz_lio: [50.0E+3, 50.0E+3, 186.9483]
lambda_xyz_lio: [0.0, 0.0, 20.0E+3]
#lambda_xyz_vio: [39.7562, 40.4794, 308.7466]
lambda_xyz_vio: [5.0, 5.0, 308.7466]

epsilon_bad_vio: [10, 10, 0.5]
epsilon_ok_vio: [0.0, 0.0, 0.5]
epsilon_bad_lio: [30.0E+3, 30.0E+3, 70.0E+3]
epsilon_ok_lio: [8.0E+3, 8.0E+3, 30.0E+3]

kx: [10.6, 11]
ky: [10.4, 11]
kz: [186.9, 187.4]

q_v_meas_l_ok: [1.0E+4, 1.0E+4, 1.0E+4]
q_l_meas_bad: [1.0E+9, 1.0E+9, 1.0E+9]
r_l_bad: [1.0E+8, 1.0E+8, 1.0E+8]
r_v_bad: [1.0E+8, 1.0E+8, 1.0E+8]

dist_threshold: 2.0
recovery: false
debug: false
debug_VIO: false
debug_LIO: false
